require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Brightcove Player SDK version
$brightcove_version = '7.0.2'

# Brightcove Player SDK
source 'https://github.com/CocoaPods/Specs.git'

# Add Brightcove repository with credentials
source 'https://repo.brightcove.com/releases' do |source|
  source.username = ENV['BRIGHTCOVE_USERNAME']
  source.password = ENV['BRIGHTCOVE_PASSWORD']
end

target 'BrightcovePlayer' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  # Comment this line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BrightcovePlayer
  pod 'Brightcove-Player-SDK', $brightcove_version
  pod 'Brightcove-Player-SDK-ExoPlayer', $brightcove_version
  pod 'Brightcove-Player-SDK-IMA', $brightcove_version
  pod 'Brightcove-Player-SDK-Omniture', $brightcove_version
  pod 'Brightcove-Player-SDK-SidecarSubtitles', $brightcove_version
  pod 'Brightcove-Player-SDK-WidevineModular', $brightcove_version
  pod 'Brightcove-Player-SDK-FairPlay', $brightcove_version
  pod 'Brightcove-Player-SDK-OnceUX', $brightcove_version
  pod 'Brightcove-Player-SDK-GoogleCast', $brightcove_version
  pod 'Brightcove-Player-SDK-Offline', $brightcove_version
  pod 'Brightcove-Player-SDK-Overlay', $brightcove_version
  pod 'Brightcove-Player-SDK-SSAI', $brightcove_version
  pod 'Brightcove-Player-SDK-TvOS', $brightcove_version
  pod 'Brightcove-Player-SDK-VR', $brightcove_version
  pod 'Brightcove-Player-SDK-WebVTT', $brightcove_version
  pod 'Brightcove-Player-SDK-360', $brightcove_version
  pod 'Brightcove-Player-SDK-AirPlay', $brightcove_version
  pod 'Brightcove-Player-SDK-AV1', $brightcove_version
  pod 'Brightcove-Player-SDK-Bitmovin', $brightcove_version
  pod 'Brightcove-Player-SDK-DFXP', $brightcove_version
  pod 'Brightcove-Player-SDK-DRM', $brightcove_version
  pod 'Brightcove-Player-SDK-FreeWheel', $brightcove_version
  pod 'Brightcove-Player-SDK-HLS', $brightcove_version
  pod 'Brightcove-Player-SDK-Mux', $brightcove_version
  pod 'Brightcove-Player-SDK-Nielsen', $brightcove_version
  pod 'Brightcove-Player-SDK-OpenMeasurement', $brightcove_version
  pod 'Brightcove-Player-SDK-Pulse', $brightcove_version
  pod 'Brightcove-Player-SDK-QoE', $brightcove_version
  pod 'Brightcove-Player-SDK-SCTE35', $brightcove_version
  pod 'Brightcove-Player-SDK-SidecarSubtitles', $brightcove_version
  pod 'Brightcove-Player-SDK-SSAI', $brightcove_version
  pod 'Brightcove-Player-SDK-Taboola', $brightcove_version
  pod 'Brightcove-Player-SDK-Tealium', $brightcove_version
  pod 'Brightcove-Player-SDK-Youbora', $brightcove_version
  pod 'Brightcove-Player-SDK-Zendesk', $brightcove_version

  target 'BrightcovePlayerTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end 